### ISSUE TITLE
Lost space in generate_forward_decl in "enum class"

### ISSUE THREAD

**Issue by Alerand** [cursey/sdkgenny#5]
https://github.com/cursey/sdkgenny/blob/0e86f4f449f9146dc0c57db7883c5b9c6f27b523/include/Genny.hpp#L845

There must be a space here, otherwise the name will merge with "class"

**Comment by cursey** [comment]
Fixed in 09a49aee14a91ac5c89b4ed0bbf0f7dc449a8aba. Thanks!
