### ISSUE TITLE
VirtualFunction generator bug

### ISSUE THREAD

**Issue by Alerand** [cursey/sdkgenny#6]
If the virtual function **has** a procedure, the generator does not append ";" at the end of the function declaration.

```C++
void generate(std::ostream& os) const override {
        os << "virtual ";
        generate_prototype(os);

        if (m_procedure.empty()) {
            os << " = 0;\n";
        }
}
```

**Comment by cursey** [comment]
Fixed in 56b7336bab16757913e19603f412e87c70ee4d75. Thanks for letting me know!
